apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../

namePrefix: dev-

commonLabels:
  environment: development

replicas:
  - name: dev-scoopdope-backend
    count: 1

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: scoopdope-backend-config
    behavior: merge
    literals:
      - LOG_LEVEL=debug
      - NODE_ENV=development
