apiVersion: v1
kind: Service
metadata:
  name: scoopdope-backend
  namespace: default
  labels:
    app: scoopdope-backend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: scoopdope-backend
  sessionAffinity: None
