apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../

namePrefix: staging-

commonLabels:
  environment: staging

replicas:
  - name: staging-scoopdope-backend
    count: 2

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: scoopdope-backend-config
    behavior: merge
    literals:
      - LOG_LEVEL=info
      - NODE_ENV=staging
